In [17]:
from sklearn.datasets import load_iris
from sklearn import tree

In [18]:
iris = load_iris()

In [19]:
print(iris.feature_names)
print(iris.target_names)
print(iris.data[0])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
[5.1 3.5 1.4 0.2]


In [21]:
import numpy as np
test_idx = [0,50,100]

#training data
train_taget = np.delete(iris.target,test_idx)
train_data = np.delete(iris.data,test_idx,axis = 0)

#testing data
test_target = iris.target[test_idx]
test_data = iris.data[test_idx]

print(train_data)

[[4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.

In [8]:
clf_train = tree.DecisionTreeClassifier()
clf_train = clf_train.fit(train_data ,train_taget)

In [9]:
print(test_target)
print(clf_train.predict(test_data))

[0 1 2]
[0 1 2]


In [10]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(iris.data,iris.target)

In [15]:
print("This Tools is Just to predict if The Isis Flower is Setosa, Versicolor or Virginica\n")
print("The main Features are sepal length(cm), sepal width(cm), petal length(cm) and petal width(cm)\nYou can mesure them using a ruler\n")

sepal_length = float(input("sepal length(cm) : "))
sepal_width = float(input("sepal width(cm) : "))

petal_length = float(input("petal length(cm) : "))
petal_width = float(input("petal width(cm) : "))


This Tools is Just to predict if The Isis Flower is setosa,versicolor or virginica

The main Features are sepal length(cm), sepal width(cm), petal length(cm) and petal width(cm)
You can mesure them using a ruler

sepal length(cm) : 1.5
sepal width(cm) : 0.3
petal length(cm) : 1
petal width(cm) : .4


In [23]:
iris_predict = clf.predict([[sepal_length,sepal_width,petal_length,petal_width]])

In [24]:
print(iris_predict)

[0]


In [25]:
if int(iris_predict) == 0:
    print("\nYour Iris is 'Setosa'")
elif int(iris_predict) == 1:
    print("\nYour Iris is 'Versicolor'")
else :
    print("\nYOur Iris is 'Virginica'")
    


Your Iris is 'Setosa'
